name: Build

on:
  push:
    branches:
      - master
      - build

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build linux/amd64
        run: docker buildx build -t insilica/srvc:latest --platform linux/amd64 --push -f Dockerfile .
